---
title: "Data Assignment 3"
output: pdf_document
date: "2025-11-05"
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{H}
  - \floatplacement{table}{H}
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
#bringing in all libraries
library(haven)
library(tidyverse)
library(stargazer)
library(modelsummary)
library(estimatr)
library(lmtest)
library(car)
library(ggpubr)
library(rstatix)
library(tinytable)
library(kableExtra)
library(tinytex)
library(mfx)
library(sandwich)
library(margins)
library(fastDummies)
library(dplyr)
library(clubSandwich)


#packages from Propensity Guide
library(gbm)
library(rms)
library(MatchIt)
library(psych)


#import datasets
dhs2015_16 <- read_dta("dhs2015-16.dta")
dhs2019_21 <- read_dta("dhs2019-21.dta")

```

### Part A - Covariate Balance

```{r echo=FALSE, message=FALSE, warning=FALSE}
#| label: Question One

# treatment = 1 & control = 0 

#designating as treatment vs control prior to joining
dhs2015_16 <- dhs2015_16 |>
  mutate(Treatment = case_when(
    bihar == 1 ~ 1,
    bihar == 0 ~ 0)) 

dhs2019_21 <- dhs2019_21 |>
  mutate(Treatment = case_when(
    bihar == 1 ~ 0,
    bihar == 0 ~ 0)) 

#combining both data sats
dhs_both <- bind_rows(dhs2015_16, dhs2019_21)

#creating dummy variables for categorical variables
dhs_both <- dummy_cols(dhs_both, select_columns = "wealth_index") 
dhs_both <- dummy_cols(dhs_both, select_columns = "caste") 
dhs_both <- dummy_cols(dhs_both, select_columns = "religion")

#creating interaction terms for Respondent's Age x Wealth Index
dhs_both <- dhs_both |>
  mutate(age_wi1 = resp_age * poorest,
         age_wi2 = resp_age * poorer,
         age_wi3 = resp_age * middle,
         age_wi4 = resp_age * richer)

#creating interaction term for Wealth Index x Husband's Education
dhs_both <- dhs_both |>
  mutate(husb_wi1 = poorest * husb_edu,
         husb_wi2 = poorer * husb_edu,
         husb_wi3 = middle * husb_edu,
         husb_wi4 = richer * husb_edu)

#creating interaction term for Religion x Wealth Index
dhs_both <- dhs_both |>
  mutate(rel_wi1 = religion * poorest,
         rel_wi2 = religion * poorer,
         rel_wi3 = religion * middle,
         rel_wi4 = religion * richer)

#creating interaction terms for Caste x Husband's Education, Religion x Caste, Respondent's Education X Years of Marriage
dhs_both <- dhs_both |>
  mutate(caste_husb = caste * husb_edu,
         caste_relg = caste * religion,
         resp_marriage = resp_edu * year_marr)

#dropping Husband's education and selecting only the relevant columns
dhs_both_1 <- dhs_both |>
   dplyr::select(
    resp_age, resp_edu, year_marr, religion, caste, husb_edu, hh_size,
    hhd_age, hhd_gender, place_residence, 
    poorest, poorer, middle, richer, 
    age_wi1, age_wi2, age_wi3, age_wi4,
    caste_husb, 
    husb_wi1, husb_wi2, husb_wi3, husb_wi4, 
    caste_relg, resp_marriage, 
    rel_wi1, rel_wi2, rel_wi3, rel_wi4,
    Treatment
  ) |>
  drop_na(husb_edu)


#labels for the columns
labels <- c(
  "Respondent's age", "Respondent's education", "Years since marriage", "Religion (Hindu = 1)", "Caste (SC/ST = 1)", "Husband's Education", "Houshold size", "Household head's age", "Household head's gender", "Place of residence", 
  
  "Poorest", "Poorer", "Middle", "Richer", 
  
  "Age x Poorest", "Age x Poorer", "Age x Middle", "Age x Richer",
  
  "Caste x Husband's Education", 
  
  "Poorest x Husband's Education", "Poorer x Husband's Education",  "Middle x Husband's Education",  "Richer x Husband's Education",
  
  "Religion x Caste", "Respondent's Education x Years Since Marriage", 
  
  "Hindu x Poorest", "Hindu x Poorer", "Hindu x Middle", "Hindu x Richer",
  
  "Treatment"
  
)

#running fake table 2
varnames <- names(dhs_both_1)

dhs_both_renamed <- dhs_both_1 |> 
  rename_with(~ labels, .cols = all_of(varnames))

datasummary_balance(~ Treatment, dhs_both_renamed, 
                    dinm_statistic = "p.value",
                    stars = TRUE,
                    fmt = fmt_sprintf("%.3f"),
                    output = "kableExtra",
                    title = "Covariate Summary Statistics") |>
   kable_styling(full_width = FALSE, 
                 bootstrap_options = c("striped", "hover"))



```

### Part B - Propensity Score Weighting

```{r echo=FALSE, message=FALSE, warning=FALSE}
#| label: Question Two

dhs_both_2 <- dhs_both_1

probit_b <- glm(Treatment ~ resp_age + resp_edu + year_marr + religion + caste + husb_edu + hh_size +
    hhd_age + hhd_gender + place_residence + 
    poorest + poorer + middle + richer + 
    age_wi1 + age_wi2 + age_wi3 + age_wi4 +
    caste_husb +
    husb_wi1 + husb_wi2 + husb_wi3 + husb_wi4 + 
    caste_relg + resp_marriage + 
    rel_wi1 + rel_wi2 + rel_wi3 + rel_wi4, 
             family = binomial(link = "probit"),
             data = dhs_both_2)

dhs_both_2$prediction <- predict(probit_b, type = "response")
dhs_both_2$prediction <- as.numeric(dhs_both_2$prediction)

#precited probabilities
dhs_2_summary <- dhs_both_2 |>
  dplyr::group_by(Treatment) |>
  dplyr::summarize(
    `Mean` = mean(prediction),
    `Median` = median(prediction),
    `Min` = min(prediction),
    `Max` = max(prediction)
  )

dhs_2_summary |>
  kbl(caption = "Summary of Predicted Propensity Scores by Treatment Group") |>
  kable_styling(
    full_width = FALSE, 
    bootstrap_options = c("striped", "hover")
  )
  

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
#| label: Question Three

dhs_both_3 <- dhs_both_1

#step 3: propensity score estimation
ps <- glm(Treatment ~ resp_age + resp_edu + year_marr + religion + caste + husb_edu + hh_size +
    hhd_age + hhd_gender + place_residence + 
    poorest + poorer + middle + richer + 
    age_wi1 + age_wi2 + age_wi3 + age_wi4 +
    caste_husb +
    husb_wi1 + husb_wi2 + husb_wi3 + husb_wi4 + 
    caste_relg + resp_marriage + 
    rel_wi1 + rel_wi2 + rel_wi3 + rel_wi4, 
             family = binomial(link = "probit"),
             data = dhs_both_3)

dhs_both_3$psvalue <- predict(ps, type = "response")
dhs_both_3$psvalue <- as.numeric(dhs_both_3$psvalue)

#step 4: weight estimation using propensity scores
dhs_both_3$weights <- ifelse(dhs_both_3$Treatment == 1, dhs_both_3$psvalue/dhs_both_3$psvalue, dhs_both_3$psvalue/(1 - dhs_both_3$psvalue))

#change names
varnames_3 <- names(dhs_both_3)
varnames_3 <- varnames_3[1:(length(varnames_3)-2)]

dhs_both_renamed_3 <- dhs_both_3 |> 
  rename_with(~ labels, .cols = all_of(varnames_3))

#create table
datasummary_balance(~ Treatment, dhs_both_renamed_3, 
                    dinm_statistic = "p.value",
                    weights = "weights",
                    stars = TRUE,
                    fmt = fmt_sprintf("%.3f"),
                    output = "kableExtra",
                    title = "Covariate Summary Statistics") |>
   kable_styling(full_width = FALSE, 
                 bootstrap_options = c("striped", "hover"))



```

### Part C - Difference in Difference Estimation

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
#| label: Question Four

dhs_both_4 <- dhs_both

dhs_both_4 <- dhs_both_4 |>
  drop_na(husb_edu)

#reweight the variables
ps <- glm(Treatment ~ resp_age + resp_edu + year_marr + religion + caste + husb_edu + hh_size +
    hhd_age + hhd_gender + place_residence + 
    poorest + poorer + middle + richer + 
    age_wi1 + age_wi2 + age_wi3 + age_wi4 +
    caste_husb +
    husb_wi1 + husb_wi2 + husb_wi3 + husb_wi4 + 
    caste_relg + resp_marriage + 
    rel_wi1 + rel_wi2 + rel_wi3 + rel_wi4, 
             family = binomial(link = "probit"),
             data = dhs_both_4)

dhs_both_4$psvalue <- predict(ps, type = "response")
dhs_both_4$psvalue <- as.numeric(dhs_both_4$psvalue)

#step 4: weight estimation using propensity scores
dhs_both_4$weights <- ifelse(dhs_both_4$Treatment == 1, dhs_both_4$psvalue/dhs_both_4$psvalue, dhs_both_4$psvalue/(1 - dhs_both_4$psvalue))

#create a district factor
dhs_both_4 <-dhs_both_4 |>
  mutate(district_year = paste0(district, "-", year))

did_IPV <- lm(ipv_d ~ resp_age + resp_edu + year_marr + religion + caste + husb_edu + hh_size +
    hhd_age + hhd_gender + place_residence + 
    poorest + poorer + middle + richer + 
    age_wi1 + age_wi2 + age_wi3 + age_wi4 +
    caste_husb +
    husb_wi1 + husb_wi2 + husb_wi3 + husb_wi4 + 
    caste_relg + resp_marriage + 
    rel_wi1 + rel_wi2 + rel_wi3 + rel_wi4 + bihar*year +factor(district), data = dhs_both_4, weights = weights)

vcov_clustered_IPV <- vcovCR(did_IPV, cluster = dhs_both_4$district_year, type = "CR1")
did_IPV_robust <- coeftest(did_IPV, vcov. =  vcov_clustered_IPV)

stargazer(did_IPV ,
          se = list(did_IPV_robust[,2]), 
          digits = 3, 
  keep = c("bihar", "year", "bihar:year"),
  dep.var.labels = c("IPV"), 
  title = "Effect of Alcohol Ban on IPV",
  style = "aer",
  table.placement = "H",
  font.size = "small",
  column.sep.width = "-25pt",
  type = "latex",
  flip = TRUE
)


```

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
#| label: Question Five

#emotional violence
did_emo <- lm(emo_d ~ resp_age + resp_edu + year_marr + religion + caste + husb_edu + hh_size +
    hhd_age + hhd_gender + place_residence + 
    poorest + poorer + middle + richer + 
    age_wi1 + age_wi2 + age_wi3 + age_wi4 +
    caste_husb +
    husb_wi1 + husb_wi2 + husb_wi3 + husb_wi4 + 
    caste_relg + resp_marriage + 
    rel_wi1 + rel_wi2 + rel_wi3 + rel_wi4 + bihar*year +factor(district), data = dhs_both_4, weights = weights)

vcov_clustered_emo <- vcovCR(did_emo, cluster = dhs_both_4$district_year, type = "CR1")
did_emo_robust <- coeftest(did_IPV, vcov. =  vcov_clustered_emo)

#phyiscal violence
did_phy <- lm(phy_d ~ resp_age + resp_edu + year_marr + religion + caste + husb_edu + hh_size +
    hhd_age + hhd_gender + place_residence + 
    poorest + poorer + middle + richer + 
    age_wi1 + age_wi2 + age_wi3 + age_wi4 +
    caste_husb +
    husb_wi1 + husb_wi2 + husb_wi3 + husb_wi4 + 
    caste_relg + resp_marriage + 
    rel_wi1 + rel_wi2 + rel_wi3 + rel_wi4 + bihar*year +factor(district), data = dhs_both_4, weights = weights)

vcov_clustered_phy <- vcovCR(did_phy, cluster = dhs_both_4$district_year, type = "CR1")
did_phy_robust <- coeftest(did_IPV, vcov. =  vcov_clustered_phy)

#sexual violence
did_sex <- lm(sexual_d ~ resp_age + resp_edu + year_marr + religion + caste + husb_edu + hh_size +
    hhd_age + hhd_gender + place_residence + 
    poorest + poorer + middle + richer + 
    age_wi1 + age_wi2 + age_wi3 + age_wi4 +
    caste_husb +
    husb_wi1 + husb_wi2 + husb_wi3 + husb_wi4 + 
    caste_relg + resp_marriage + 
    rel_wi1 + rel_wi2 + rel_wi3 + rel_wi4 + bihar*year +factor(district), data = dhs_both_4, weights = weights)

vcov_clustered_sex <- vcovCR(did_sex, cluster = dhs_both_4$district_year, type = "CR1")
did_sex_robust <- coeftest(did_sex, vcov. =  vcov_clustered_sex)

#controlling
did_control <- lm(control_d ~ resp_age + resp_edu + year_marr + religion + caste + husb_edu + hh_size +
    hhd_age + hhd_gender + place_residence + 
    poorest + poorer + middle + richer + 
    age_wi1 + age_wi2 + age_wi3 + age_wi4 +
    caste_husb +
    husb_wi1 + husb_wi2 + husb_wi3 + husb_wi4 + 
    caste_relg + resp_marriage + 
    rel_wi1 + rel_wi2 + rel_wi3 + rel_wi4 + bihar*year +factor(district), data = dhs_both_4, weights = weights)

vcov_clustered_control <- vcovCR(did_control, cluster = dhs_both_4$district_year, type = "CR1")
did_control_robust <- coeftest(did_control, vcov. =  vcov_clustered_control)

#making into one section
library(stargazer)

stargazer(
  did_emo, did_phy, did_control, did_sex, 
  se = list(did_emo_robust[,2], 
            did_phy_robust[,2], 
            did_control_robust[,2], 
            did_sex_robust[,2]), 
  digits = 3, 
  keep = c("bihar", "year", "bihar:year"),
  dep.var.labels = c("Emotional", "Physical", "Control", "Sexual"), 
  title = "Effect of Alcohol Ban on Different Aspects of IPV",
  style = "aer",
  table.placement = "H",
  font.size = "small",
  column.sep.width = "-25pt",
  type = "latex",
  flip = TRUE
)



          
          
           
         
```


### Part D - Instrumental Variables Regression

```{r, echo = FALSE, message = FALSE, warning = FALSE}

```
